### ISSUE TITLE
Putting this addon up for adoption?

### ISSUE THREAD

**Issue by patocallaghan** [adopted-ember-addons/ember-data-factory-guy#419]
Just capturing some discussion happening over in https://github.com/danielspaniel/ember-data-factory-guy/issues/417#issuecomment-630466152

![image](https://user-images.githubusercontent.com/685034/82266264-27fd2380-9961-11ea-8d8c-0838ebfd5e35.png)

When an original owner no longer has time to maintain the addon, there is a place where the addon can be "put up for adoption." Melanie Sumner has created [adopted-ember-addons](https://github.com/adopted-ember-addons). See the dedicated [#ember-adopted-addons channel](https://discord.com/channels/480462759797063690/525367494400278538) in the Ember Discord.

Would you consider allowing us to adopt ember-data-factory-guy so that the addon may continue to provide useful service to the community?

**Comment by luxferresum** [comment]
@danielspaniel any chance we can get this adopted?

**Comment by danielspaniel** [comment]
yes, please .. whatever you can do to help is appreciated.  not sure how to proceed though

**Comment by patocallaghan** [comment]
@danielspaniel I think the next steps would be to head to the Ember Discord #adopted-ember-addons channel and confirm that you'd like to put it up for adoption. I think there will be a process to transfer ownership to the [adopted-ember-addons](https://github.com/adopted-ember-addons)org then.

**Comment by patocallaghan** [comment]
After discussions in the Ember Discord with @luxferresum and @danielspaniel we have officially agreed to move this addon to the Ember Adopted Addons org. To do so we must implement the following tasks:

### [Addon Transfer Checklist](https://github.com/adopted-ember-addons/program-guidelines)
These are the things that need to done to transfer your addon:
* [ ] To get your addon adopted, please ping one of the adopted-ember-addons org owners (`@Melanie#1618`, `@Alon#3707`, or `@knownasilya#9990`) in the Ember Discord chat in the #adopted-ember-addons channel and let them know what repository you'd like to transfer.
* [ ] Once they are aware, complete the Addon Transfer checklist (below).
   * [ ] Update the repository field of the package.json to point to the new location.
   * [ ] If any demo URL or homepage is referenced, it should be updated. At the very least, file an issue on the repository so the adopter can fix.
   * [ ] Ensure Release practices are documented.
   * [ ] Add at least one of the adopted-ember-addons org owners (melsumner, alonbukai, or knownasilya) to the maintainers of the package on npm. Make sure they have all admin permissions. Remove other maintainers, if reasonable.
* [ ] After the checklist is complete, transfer the repository to one of them here on GitHub.
* [ ] The org owner is then responsible to transfer the addon to this org (Adopted Ember Addons).

**Comment by patocallaghan** [comment]
I've implemented the changes required in the "Addon Transfer checklist".

Thanks @danielspaniel 🙌  For the next step could you transfer ownership of the repo to @MelSumner please? She can then move the repo to the adopted-ember-addons org. 

> After the checklist is complete, transfer the repository to one of them here on GitHub.

**Comment by danielspaniel** [comment]
there is no transfer button on github  .. so not sure how to do that ( i looked it up but they suggest you need enterprise github to do it )

**Comment by patocallaghan** [comment]
I think there's a Transfer button in the repo's settings section which allows you to transfer to another user https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by danielspaniel** [comment]
thanks, duh .. i did not scroll down far enough .. thanks for helping. I transfered just now

**Comment by patocallaghan** [comment]
@melsumner the repo should be ready to be moved to the adopted-ember-addons org now. You should have ownership of this repo.

**Comment by patocallaghan** [comment]
@danielspaniel sorry to bother. any chance you could resend the "Transfer" invite from above please? It appears the last transfer invite has now expired.

**Comment by danielspaniel** [comment]
all set Pat

**Comment by patocallaghan** [comment]
Thanks everyone for your help! The addon has been transferred to the adopted-ember-addons org.

**Comment by danielspaniel** [comment]
whoooooooo haaaaaa!
