### ISSUE TITLE
Bump pretender to 3.4.3

### ISSUE THREAD

**Issue by jcardali** [adopted-ember-addons/ember-data-factory-guy#427]
Would like to bump pretender in a project that also uses ember-data-factory-guy, which currently causes a version mismatch because the highest that ember-data-factory-guy's pretender can go up to is 3.0.5, which is [nine months old](https://www.npmjs.com/package/pretender)

According to [pretender's changelog](https://github.com/pretenderjs/pretender/blob/master/CHANGELOG.md), there have been no breaking changes since 3.0.1.

~~I was able to clone the repo and do the bump locally, and all tests pass, however I'm unable to push the branch for some reason.~~

**Comment by patocallaghan** [comment]
Released in 3.9.8
