### ISSUE TITLE
Could not find module `@ember/debug`

### ISSUE THREAD

**Issue by mehran-naghizadeh** [adopted-ember-addons/ember-data-factory-guy#473]
Hi

I have updated an Ember app from `ember-source 3.24` to `3.25` along with ember-data and other related stuff. Now, the `ember serve` command works but when visiting the page, I get this error  in the browser console and nothing is rendered on the page:

> Uncaught Error: Could not find module `@ember/debug` imported from `ember-data-factory-guy/mocks/exposed-request-functions`
>     at missingModule (vendor.js:259:11)
>     at findModule (vendor.js:270:7)
>     at Module.findDeps (vendor.js:180:24)
>     at findModule (vendor.js:274:11)
>     at Module.findDeps (vendor.js:180:24)
>     at findModule (vendor.js:274:11)
>     at Module.findDeps (vendor.js:180:24)
>     at findModule (vendor.js:274:11)
>     at requireModule (vendor.js:36:15)
>     at r (vendor.js:188:14)

In my package.json, I have got:

```
"devDependencies": {
  ...
  "ember-data-factory-guy": "^3.9.11",
  ...
},
```

**Comment by patocallaghan** [comment]
@mehran-naghizadeh I don't think this is a bug with ember-data-factory-guy. It's more likely to do with how your dependencies are resolving. [That file](https://github.com/adopted-ember-addons/ember-data-factory-guy/blame/master/addon/mocks/exposed-request-functions.js) has had the `@ember/debug` import in it for ~4 years.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/685034/207725179-9cdcd14a-a664-49ea-bdce-9cd479f498d6.png">

A possible area to look into is making sure your dependencies are resolving to a recent version of https://github.com/ember-cli/ember-rfc176-data. I'm going to close this but please re-open if you disagree.
