### ISSUE TITLE
can we publish a release

### ISSUE THREAD

**Issue by Techn1x** [adopted-ember-addons/ember-data-factory-guy#483]
I hate to be that guy but any chance we could get a patch release published? (please :smile: )

Hoping to consume the object assign deprecation fix https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/481

Otherwise it's a bit hard to see the forest from the trees in the dev console when booting up with a lot of models :)
![Screenshot from 2023-02-22 17-24-50](https://user-images.githubusercontent.com/1049837/220551770-849e1281-f5f2-4483-8948-faa9161d4627.png)
![Screenshot from 2023-02-22 17-25-00](https://user-images.githubusercontent.com/1049837/220551763-6e073e34-bf37-4480-82d0-43217e70bfa2.png)

**Comment by Techn1x** [comment]
(I know I can filter the console, but I do have some assigns deprecations that aren't FG related, so it gets tricky to identify)

**Comment by RosarioAleCali** [comment]
I agree with @Techn1x... it would be much appreciated!

**Comment by Techn1x** [comment]
@patocallaghan friendly ping

**Comment by patocallaghan** [comment]
I’ll cut an alpha later but it won’t be the full major release version

**Comment by patocallaghan** [comment]
@Techn1x @RosarioAleCali I've released the change in [v4.0.0-alpha.1](https://github.com/adopted-ember-addons/ember-data-factory-guy/releases/tag/v4.0.0-alpha.1)

**Comment by Techn1x** [comment]
Thanks Pat, that's a fair point and I think the alpha release is a good way to tackle it.

Given that this tool is for dev / testing, I do wonder if we need to care that much about dropping IE - but I understand the importance of semver :)

**Comment by patocallaghan** [comment]
@Techn1x Yeah you just don't know how folks are using this tool but at least following proper semver makes that versioning decision for us 👍
